Move file limit from startup to execute_query

diff --git a/init.d/shimsvc b/init.d/shimsvc
--- a/init.d/shimsvc
+++ b/init.d/shimsvc
@@ -13,21 +13,15 @@
 # Locate scidb heuristics
 SCIDB_DIR=$(dirname $(dirname $(which scidb 2>/dev/null) 2>/dev/null) 2>/dev/null)
 if test -z "${SCIDB_DIR}"; then
-    if test -d /opt/scidb; then
-	SCIDB_DIR=$(dirname $(dirname $(find /opt/scidb/ -name shim 2>/dev/null | tail -n 1) 2>/dev/null) 2>/dev/null)
-	#    SCIDB_DIR=$(ls -t /opt/scidb | head -n 1)
-	#    if test -n "${SCIDB_DIR}"; then SCIDB_DIR="/opt/scidb/${SCIDB_DIR}";fi
-    fi
-    if test -z "${SCIDB_DIR}"; then
-	if test -d /home/jkinchen/scidb/scidbtrunk/stage/install; then
-	    SCIDB_DIR=$(dirname $(dirname $(find /home/jkinchen/scidb/scidbtrunk/stage/install -name shim 2>/dev/null | tail -n 1) 2>/dev/null) 2>/dev/null)
-	fi
-    fi
-
-    if test -z "${SCIDB_DIR}"; then
-	echo "Error, can't find SciDB, is it in the PATH?" 2>&1
-	exit 1
-    fi
+  if test -d /opt/scidb; then
+    SCIDB_DIR=$(dirname $(dirname $(find /opt/scidb/ -name shim 2>/dev/null | tail -n 1) 2>/dev/null) 2>/dev/null)
+#    SCIDB_DIR=$(ls -t /opt/scidb | head -n 1)
+#    if test -n "${SCIDB_DIR}"; then SCIDB_DIR="/opt/scidb/${SCIDB_DIR}";fi
+  fi
+  if test -z "${SCIDB_DIR}"; then
+    echo "Error, can't find SciDB, is it in the PATH?" 2>&1
+    exit 1
+  fi
 fi
 
 export LD_LIBRARY_PATH="${SCIDB_DIR}/lib:${SCIDB_DIR}/3rdparty/boost/lib"
@@ -49,7 +43,6 @@ if test -f "/var/lib/shim/conf"; then
   TIMEOUT="$(cat /var/lib/shim/conf | sed -n /^time/p | cut -d '=' -f 2 | tr -d '\r')"
   SAVE_INSTANCE_ID="$(cat /var/lib/shim/conf | sed -n /^instance/p | cut -d '=' -f 2 | tr -d '\r')"
   AIO="$(cat /var/lib/shim/conf | sed -n /^aio/p | cut -d '=' -f 2 | tr -d '\r')"
-  TMP_SZ_LIMIT="$(cat /var/lib/shim/conf | sed -n /^file_limit/p | cut -d '=' -f 2 | tr -d '\r')"
 # Build up shim command line options
   test -n "${PORTS}" && PORTS="-p ${PORTS}"
   test -n "${TMPD}" && TMPD="-t ${TMPD}"
@@ -59,17 +52,16 @@ if test -f "/var/lib/shim/conf"; then
   test -n "${TIMEOUT}" && TIMEOUT="-o ${TIMEOUT}"
   test -n "${SAVE_INSTANCE_ID}" && SAVE_INSTANCE_ID="-i ${SAVE_INSTANCE_ID}"
   test -n "${AIO}" && AIO="-a"
-  test -n "${TMP_SZ_LIMIT}" && TMP_SZ_LIMIT="-l ${TMP_SZ_LIMIT}"
 fi
 
 case $1 in
         test)
             echo "Command line"
-            echo "su $USER -c \"'${SHIM}' $PORTS $SCIDBPORT $TMPD $MAX_SESSIONS $TIMEOUT $SAVE_INSTANCE_ID $AIO $TMP_SZ_LIMIT\""
+            echo "su $USER -c \"'${SHIM}' $PORTS $SCIDBPORT $TMPD $MAX_SESSIONS $TIMEOUT $SAVE_INSTANCE_ID $AIO\""
             ;;
         start)
             echo "Starting shim"
-            su $USER -c "'${SHIM}' $PORTS $SCIDBPORT $TMPD $MAX_SESSIONS $TIMEOUT $SAVE_INSTANCE_ID $AIO $TMP_SZ_LIMIT"
+            su $USER -c "'${SHIM}' $PORTS $SCIDBPORT $TMPD $MAX_SESSIONS $TIMEOUT $SAVE_INSTANCE_ID $AIO"
             ;;
         restart)
             $0 stop
@@ -77,9 +69,9 @@ case $1 in
             ;;
         status)
             Q=$(ps aux | egrep -v 'grep|shimsvc' | grep shim 2>/dev/null)
-            if test -z "${Q}"; then
-              echo "Shim process not found";
-              exit 1;
+            if test -z "${Q}"; then 
+              echo "Shim process not found"; 
+              exit 1; 
             fi
             echo "Shim process ${Q}"; exit 0
             ;;
